/**
 * Static voice catalogue from freetts.ru.
 * Source: https://freetts.ru/api/v1/select (snapshot 2025-01-15)
 *
 * 57 languages, 298 voices (148 male / 150 female).
 * The API itself is protected by a WAF and cannot be called from server-side
 * code, so we ship the catalogue as a static asset.
 */

export interface FreeTtsLanguage {
  /** ISO 639-1 language code, e.g. "ru", "en", "zh" */
  code: string;
  /** Russian display name, e.g. "Русский" */
  name: string;
}

export interface FreeTtsVoice {
  /** Voice code, e.g. "ru-RU001", "en-US058" */
  code: string;
  /** Russian voice name, e.g. "Ермилов" */
  name: string;
  /** "m" for male, "f" for female */
  gender: "m" | "f";
}

export const FREETTS_LANGUAGES: FreeTtsLanguage[] = [
  { code: "en", name: "Английский" },
  { code: "af", name: "Африкаанс" },
  { code: "am", name: "Амхарский" },
  { code: "ar", name: "Арабский" },
  { code: "az", name: "Азербайджанский" },
  { code: "bg", name: "Болгарский" },
  { code: "bn", name: "Бенгальский" },
  { code: "bs", name: "Боснийский" },
  { code: "my", name: "Бирманский" },
  { code: "cy", name: "Валлийский" },
  { code: "hu", name: "Венгерский" },
  { code: "el", name: "Греческий" },
  { code: "gl", name: "Галисийский" },
  { code: "gu", name: "Гуджарати" },
  { code: "ka", name: "Грузинский" },
  { code: "da", name: "Датский" },
  { code: "kn", name: "Дравидийский (Каннада)" },
  { code: "es", name: "Испанский" },
  { code: "id", name: "Индонезийский" },
  { code: "ga", name: "Ирландский" },
  { code: "he", name: "Иврит" },
  { code: "is", name: "Исландский" },
  { code: "it", name: "Итальянский" },
  { code: "ko", name: "Корейский" },
  { code: "ca", name: "Каталанский" },
  { code: "kk", name: "Казахский" },
  { code: "km", name: "Кхмерский" },
  { code: "lo", name: "Лаосский" },
  { code: "lt", name: "Литовский" },
  { code: "lv", name: "Латышский" },
  { code: "mk", name: "Македонский" },
  { code: "ml", name: "Малайялам" },
  { code: "mn", name: "Монгольский" },
  { code: "mr", name: "Маратхи" },
  { code: "ms", name: "Малайский" },
  { code: "mt", name: "Мальтийский" },
  { code: "de", name: "Немецкий" },
  { code: "nb", name: "Норвежский" },
  { code: "ne", name: "Непальский" },
  { code: "nl", name: "Нидерландский" },
  { code: "pt", name: "Португальский" },
  { code: "fa", name: "Персидский" },
  { code: "pl", name: "Польский" },
  { code: "ps", name: "Пушту" },
  { code: "ru", name: "Русский" },
  { code: "ro", name: "Румынский" },
  { code: "tr", name: "Турецкий" },
  { code: "uk", name: "Украинский" },
  { code: "fr", name: "Французский" },
  { code: "fi", name: "Финский" },
  { code: "fil", name: "Филиппинский" },
  { code: "hi", name: "Хинди" },
  { code: "hr", name: "Хорватский" },
  { code: "cs", name: "Чешский" },
  { code: "et", name: "Эстонский" },
  { code: "ja", name: "Японский" },
  { code: "jv", name: "Яванский" },
];

export const FREETTS_VOICES: FreeTtsVoice[] = [
  { code: "ru-RU001", name: "Ермилов", gender: "m" },
  { code: "ru-RU002", name: "Николай", gender: "m" },
  { code: "ru-RU003", name: "Евгений", gender: "m" },
  { code: "ru-RU004", name: "Анатолий", gender: "m" },
  { code: "ru-RU005", name: "Константин", gender: "m" },
  { code: "ru-RU006", name: "Захар", gender: "m" },
  { code: "ru-RU007", name: "Оксана", gender: "f" },
  { code: "ru-RU008", name: "Александра", gender: "f" },
  { code: "ru-RU009", name: "Татьяна", gender: "f" },
  { code: "ru-RU010", name: "Анастасия", gender: "f" },
  { code: "ru-RU011", name: "Жанна", gender: "f" },
  { code: "ru-RU012", name: "Анжелика", gender: "f" },
  { code: "ru-RU013", name: "Никита", gender: "m" },
  { code: "ru-RU014", name: "Наталья", gender: "f" },
  { code: "ru-RU015", name: "Абрамова", gender: "f" },
  { code: "ru-SU016", name: "Левитан", gender: "m" },
  { code: "ru-RU017", name: "Смоки", gender: "m" },
  { code: "uk-UA001", name: "Захар", gender: "m" },
  { code: "uk-UA002", name: "Евгений", gender: "m" },
  { code: "tr-TR001", name: "Мустафа", gender: "m" },
  { code: "tr-TR002", name: "Зейнеп", gender: "f" },
  { code: "en-US058", name: "Грейс", gender: "f" },
  { code: "en-US059", name: "Мэтью", gender: "m" },
  { code: "en-US060", name: "Остин", gender: "m" },
  { code: "en-US061", name: "Эрл", gender: "m" },
  { code: "en-US062", name: "Уилфред", gender: "m" },
  { code: "en-GB034", name: "Уинстон", gender: "m" },
  { code: "en-GB035", name: "Трэвис", gender: "m" },
  { code: "en-AU017", name: "Бренда", gender: "f" },
  { code: "en-AU018", name: "Саймон", gender: "m" },
  { code: "fr-FR028", name: "Фабьен", gender: "m" },
  { code: "fr-FR029", name: "Жерар", gender: "m" },
  { code: "de-DE037", name: "Хелга", gender: "f" },
  { code: "de-DE038", name: "Манфред", gender: "m" },
  { code: "es-ES017", name: "Альваро", gender: "m" },
  { code: "es-MX004", name: "Эдмундо", gender: "m" },
  { code: "pt-PT014", name: "Дэуса", gender: "f" },
  { code: "pt-PT015", name: "Жуана", gender: "f" },
  { code: "pt-PT016", name: "Лагос", gender: "m" },
  { code: "id-ID011", name: "Бесари", gender: "f" },
  { code: "ja-JP015", name: "Сумико", gender: "f" },
  { code: "ja-JP016", name: "Харука", gender: "f" },
  { code: "ja-JP017", name: "Широ", gender: "m" },
  { code: "ko-KR016", name: "Шин", gender: "m" },
  { code: "ko-KR017", name: "Ханьюл ", gender: "m" },
  { code: "ko-KR018", name: "Тхан", gender: "f" },
  { code: "ru-RU500", name: "Маргарита", gender: "f" },
  { code: "af-ZA002", name: "Адри", gender: "f" },
  { code: "af-ZA003", name: "Виллем", gender: "m" },
  { code: "am-ET002", name: "Мекдес", gender: "f" },
  { code: "am-ET001", name: "Амеха", gender: "m" },
  { code: "ar-AE001", name: "Фатима", gender: "f" },
  { code: "ar-AE002", name: "Хамдан", gender: "m" },
  { code: "ar-BH002", name: "Лейла", gender: "f" },
  { code: "ar-BH001", name: "Али", gender: "m" },
  { code: "ar-DZ001", name: "Амина", gender: "f" },
  { code: "ar-DZ002", name: "Исмаэль", gender: "m" },
  { code: "ar-EG001", name: "Сальма", gender: "f" },
  { code: "ar-EG002", name: "Шакир", gender: "m" },
  { code: "ar-IQ002", name: "Рана", gender: "f" },
  { code: "ar-IQ001", name: "Бассель", gender: "m" },
  { code: "ar-JO001", name: "Сана", gender: "f" },
  { code: "ar-JO002", name: "Тайм", gender: "m" },
  { code: "ar-KW002", name: "Нура", gender: "f" },
  { code: "ar-KW001", name: "Фахед", gender: "m" },
  { code: "ar-LB001", name: "Лейла", gender: "f" },
  { code: "ar-LB002", name: "Рами", gender: "m" },
  { code: "ar-LY001", name: "Иман", gender: "f" },
  { code: "ar-LY002", name: "Омар", gender: "m" },
  { code: "ar-MA002", name: "Мауна", gender: "f" },
  { code: "ar-MA001", name: "Джамал", gender: "m" },
  { code: "ar-OM002", name: "Айша", gender: "f" },
  { code: "ar-OM001", name: "Абдулла", gender: "m" },
  { code: "ar-QA001", name: "Амаль", gender: "f" },
  { code: "ar-QA002", name: "Моаз", gender: "m" },
  { code: "ar-SA002", name: "Зария", gender: "f" },
  { code: "ar-SA001", name: "Хамед", gender: "m" },
  { code: "ar-SY001", name: "Амани", gender: "f" },
  { code: "ar-SY002", name: "Лейт", gender: "m" },
  { code: "ar-TN002", name: "Рим", gender: "f" },
  { code: "ar-TN001", name: "Хеди", gender: "m" },
  { code: "ar-YE001", name: "Марьям", gender: "f" },
  { code: "ar-YE002", name: "Салех", gender: "m" },
  { code: "az-AZ002", name: "Бану", gender: "f" },
  { code: "az-AZ001", name: "Бабек", gender: "m" },
  { code: "bg-BG003", name: "Калина", gender: "f" },
  { code: "bg-BG002", name: "Борислав", gender: "m" },
  { code: "bn-BD001", name: "Набанита", gender: "f" },
  { code: "bn-BD002", name: "Прадип", gender: "m" },
  { code: "bn-IN006", name: "Танишаа", gender: "f" },
  { code: "bn-IN005", name: "Башкарь", gender: "m" },
  { code: "bs-BA002", name: "Весна", gender: "f" },
  { code: "bs-BA001", name: "Горан", gender: "m" },
  { code: "ca-ES002", name: "Джоана", gender: "f" },
  { code: "ca-ES004", name: "Энрик", gender: "m" },
  { code: "cs-CZ004", name: "Власта", gender: "f" },
  { code: "cs-CZ003", name: "Антонин", gender: "m" },
  { code: "cy-GB002", name: "Ниа", gender: "f" },
  { code: "cy-GB001", name: "Алед", gender: "m" },
  { code: "da-DK009", name: "Кристель", gender: "f" },
  { code: "da-DK010", name: "Йеппе", gender: "m" },
  { code: "de-AT001", name: "Ингрид", gender: "f" },
  { code: "de-AT002", name: "Йонас", gender: "m" },
  { code: "de-CH002", name: "Лени", gender: "f" },
  { code: "de-CH001", name: "Ян", gender: "m" },
  { code: "de-DE014", name: "Катя", gender: "f" },
  { code: "de-DE018", name: "Конрад", gender: "m" },
  { code: "de-DE015", name: "Амала", gender: "f" },
  { code: "de-DE022", name: "Киллиан", gender: "m" },
  { code: "el-GR003", name: "Афина", gender: "f" },
  { code: "el-GR004", name: "Несторас", gender: "m" },
  { code: "en-AU010", name: "Наташа", gender: "f" },
  { code: "en-AU011", name: "Уильям", gender: "m" },
  { code: "en-CA001", name: "Клара", gender: "f" },
  { code: "en-CA002", name: "Лиам", gender: "m" },
  { code: "en-GB024", name: "Соня", gender: "f" },
  { code: "en-GB023", name: "Райан", gender: "m" },
  { code: "en-GB012", name: "Либби", gender: "f" },
  { code: "en-GB019", name: "Мэйси(детский)", gender: "f" },
  { code: "en-GB025", name: "Томас", gender: "m" },
  { code: "en-HK002", name: "Ян", gender: "f" },
  { code: "en-HK001", name: "Сэм", gender: "m" },
  { code: "en-IE002", name: "Эмили", gender: "f" },
  { code: "en-IE001", name: "Коннор", gender: "m" },
  { code: "en-IN009", name: "Нирджа", gender: "f" },
  { code: "en-IN010", name: "Прабхат", gender: "m" },
  { code: "en-KE001", name: "Асилия", gender: "f" },
  { code: "en-KE002", name: "Чилемба", gender: "m" },
  { code: "en-NG002", name: "Эзинн", gender: "f" },
  { code: "en-NG001", name: "Абео", gender: "m" },
  { code: "en-NZ002", name: "Молли", gender: "f" },
  { code: "en-NZ001", name: "Митчелл", gender: "m" },
  { code: "en-PH002", name: "Роза", gender: "f" },
  { code: "en-PH001", name: "Джеймс", gender: "m" },
  { code: "en-SG001", name: "Луна", gender: "f" },
  { code: "en-SG002", name: "Уэйн", gender: "m" },
  { code: "en-TZ002", name: "Имани", gender: "f" },
  { code: "en-TZ001", name: "Элиму", gender: "m" },
  { code: "en-US024", name: "Дженни", gender: "f" },
  { code: "en-US026", name: "Бенджамин", gender: "m" },
  { code: "en-US029", name: "Ария", gender: "f" },
  { code: "en-US027", name: "Янтарь", gender: "f" },
  { code: "en-US028", name: "Анна(детский)", gender: "f" },
  { code: "en-US030", name: "Эшли", gender: "f" },
  { code: "en-US031", name: "Брэндон", gender: "m" },
  { code: "en-US032", name: "Кристофер", gender: "m" },
  { code: "en-US033", name: "Кора", gender: "f" },
  { code: "en-US034", name: "Элизабет", gender: "f" },
  { code: "en-US035", name: "Эрик", gender: "m" },
  { code: "en-US036", name: "Джейкоб", gender: "m" },
  { code: "en-US037", name: "Мишель", gender: "f" },
  { code: "en-US038", name: "Моника", gender: "f" },
  { code: "en-ZA001", name: "Лия", gender: "f" },
  { code: "en-ZA002", name: "Люк", gender: "m" },
  { code: "es-AR001", name: "Елена", gender: "f" },
  { code: "es-AR002", name: "Томас", gender: "m" },
  { code: "es-BO002", name: "София", gender: "f" },
  { code: "es-BO001", name: "Марсело", gender: "m" },
  { code: "es-CL001", name: "Каталина", gender: "f" },
  { code: "es-CL002", name: "Лоренцо", gender: "m" },
  { code: "es-CO002", name: "Саломея", gender: "f" },
  { code: "es-CO001", name: "Гонсало", gender: "m" },
  { code: "es-CR002", name: "Мария", gender: "f" },
  { code: "es-CR001", name: "Хуан", gender: "m" },
  { code: "es-CU001", name: "Белкис", gender: "f" },
  { code: "es-CU002", name: "Мануэль", gender: "m" },
  { code: "es-DO002", name: "Рамона", gender: "f" },
  { code: "es-DO001", name: "Эмилио", gender: "m" },
  { code: "es-EC001", name: "Андреа", gender: "f" },
  { code: "es-EC002", name: "Луис", gender: "m" },
  { code: "es-ES009", name: "Эльвира", gender: "f" },
  { code: "es-ES008", name: "Альваро", gender: "m" },
  { code: "es-GQ002", name: "Тереза", gender: "f" },
  { code: "es-GQ001", name: "Хавьер", gender: "m" },
  { code: "es-GT002", name: "Марта", gender: "f" },
  { code: "es-GT001", name: "Андрес", gender: "m" },
  { code: "es-HN002", name: "Карла", gender: "f" },
  { code: "es-HN001", name: "Карлос", gender: "m" },
  { code: "es-MX001", name: "Далия", gender: "f" },
  { code: "es-MX002", name: "Хорхе", gender: "m" },
  { code: "es-NI002", name: "Иоланда", gender: "f" },
  { code: "es-NI001", name: "Федерико", gender: "m" },
  { code: "es-PA001", name: "Маргарита", gender: "f" },
  { code: "es-PA002", name: "Роберто", gender: "m" },
  { code: "es-PE002", name: "Камила", gender: "f" },
  { code: "es-PE001", name: "Алекс", gender: "m" },
  { code: "es-PR001", name: "Карина", gender: "f" },
  { code: "es-PR002", name: "Виктор", gender: "m" },
  { code: "es-PY002", name: "Таня", gender: "f" },
  { code: "es-PY001", name: "Марио", gender: "m" },
  { code: "es-SV001", name: "Лорена", gender: "f" },
  { code: "es-SV002", name: "Родриго", gender: "m" },
  { code: "es-US010", name: "Палома", gender: "f" },
  { code: "es-US009", name: "Алонсо", gender: "m" },
  { code: "es-UY002", name: "Валентина", gender: "f" },
  { code: "es-UY001", name: "Матео", gender: "m" },
  { code: "es-VE001", name: "Паола", gender: "f" },
  { code: "es-VE002", name: "Себастьян", gender: "m" },
  { code: "et-EE001", name: "Ану", gender: "f" },
  { code: "et-EE002", name: "Керт", gender: "m" },
  { code: "fa-IR001", name: "Дилара", gender: "f" },
  { code: "fa-IR002", name: "Фарид", gender: "m" },
  { code: "fi-FI003", name: "Сельма", gender: "f" },
  { code: "fi-FI004", name: "Харри", gender: "m" },
  { code: "fi-FI005", name: "Нура", gender: "f" },
  { code: "fil-PH010", name: "Блессика", gender: "f" },
  { code: "fil-PH009", name: "Анджело", gender: "m" },
  { code: "fr-BE001", name: "Шарлин", gender: "f" },
  { code: "fr-BE002", name: "Джерард", gender: "m" },
  { code: "fr-CA009", name: "Сильви", gender: "f" },
  { code: "fr-CA011", name: "Жан", gender: "m" },
  { code: "fr-CA010", name: "Антуан", gender: "m" },
  { code: "fr-CH001", name: "Ариан", gender: "f" },
  { code: "fr-CH002", name: "Фабрис", gender: "m" },
  { code: "fr-FR016", name: "Дениз", gender: "f" },
  { code: "fr-FR018", name: "Анри", gender: "m" },
  { code: "fr-FR017", name: "Элоиза(детский)", gender: "f" },
  { code: "ga-IE002", name: "Орла", gender: "f" },
  { code: "ga-IE001", name: "Колм", gender: "m" },
  { code: "gl-ES002", name: "Сабела", gender: "f" },
  { code: "gl-ES001", name: "Рой", gender: "m" },
  { code: "gu-IN005", name: "Дхвани", gender: "f" },
  { code: "gu-IN006", name: "Ниранджан", gender: "m" },
  { code: "he-IL002", name: "Хила", gender: "f" },
  { code: "he-IL001", name: "Аври", gender: "m" },
  { code: "hi-IN010", name: "Свара", gender: "f" },
  { code: "hi-IN009", name: "Мадхур", gender: "m" },
  { code: "hr-HR001", name: "Габриела", gender: "f" },
  { code: "hr-HR002", name: "Сречко", gender: "m" },
  { code: "hu-HU003", name: "Ноэми", gender: "f" },
  { code: "hu-HU004", name: "Тамас", gender: "m" },
  { code: "id-ID010", name: "Гадис", gender: "f" },
  { code: "id-ID009", name: "Арди", gender: "m" },
  { code: "is-IS002", name: "Гудрун", gender: "f" },
  { code: "is-IS003", name: "Гуннар", gender: "m" },
  { code: "it-IT011", name: "Эльза", gender: "f" },
  { code: "it-IT009", name: "Изабелла", gender: "f" },
  { code: "it-IT010", name: "Диего", gender: "m" },
  { code: "ja-JP009", name: "Нанами", gender: "f" },
  { code: "ja-JP010", name: "Кейта", gender: "m" },
  { code: "jv-ID002", name: "Сити", gender: "f" },
  { code: "jv-ID001", name: "Димас", gender: "m" },
  { code: "ka-GE001", name: "Эка", gender: "f" },
  { code: "ka-GE002", name: "Георгий", gender: "m" },
  { code: "kk-KZ004", name: "Айгуль", gender: "f" },
  { code: "kk-KZ005", name: "Даулет", gender: "m" },
  { code: "km-KH002", name: "Среймом", gender: "f" },
  { code: "km-KH001", name: "Писет", gender: "m" },
  { code: "kn-IN006", name: "Сапна", gender: "f" },
  { code: "kn-IN005", name: "Гаган", gender: "m" },
  { code: "ko-KR009", name: "СолнцеПривет", gender: "f" },
  { code: "ko-KR010", name: "Инджун", gender: "m" },
  { code: "lo-LA002", name: "Кеомани", gender: "f" },
  { code: "lo-LA001", name: "Чантавонг", gender: "m" },
  { code: "lt-LT002", name: "На", gender: "f" },
  { code: "lt-LT001", name: "Леонас", gender: "m" },
  { code: "lv-LV002", name: "Эверита", gender: "f" },
  { code: "lv-LV003", name: "Нильс", gender: "m" },
  { code: "mk-MK002", name: "Мария", gender: "f" },
  { code: "mk-MK001", name: "Александр", gender: "m" },
  { code: "ml-IN006", name: "Собхана", gender: "f" },
  { code: "ml-IN005", name: "Мидхун", gender: "m" },
  { code: "mn-MN002", name: "Есуи", gender: "f" },
  { code: "mn-MN001", name: "Батаа", gender: "m" },
  { code: "mr-IN001", name: "Аарохи", gender: "f" },
  { code: "mr-IN002", name: "Манохар", gender: "m" },
  { code: "ms-MY010", name: "Ясмин", gender: "f" },
  { code: "ms-MY009", name: "Осман", gender: "m" },
  { code: "mt-MT001", name: "Милость", gender: "f" },
  { code: "mt-MT002", name: "Джозеф", gender: "m" },
  { code: "my-MM001", name: "Нилар", gender: "f" },
  { code: "my-MM002", name: "Тиха", gender: "m" },
  { code: "nb-NO011", name: "Пернилла", gender: "f" },
  { code: "nb-NO012", name: "Финн", gender: "m" },
  { code: "nb-NO013", name: "Иселин", gender: "f" },
  { code: "ne-NP001", name: "Хемкала", gender: "f" },
  { code: "ne-NP002", name: "Сагар", gender: "m" },
  { code: "nl-BE006", name: "Дена", gender: "f" },
  { code: "nl-BE005", name: "Арно", gender: "m" },
  { code: "nl-NL012", name: "Фенна", gender: "f" },
  { code: "nl-NL013", name: "Мартен", gender: "m" },
  { code: "nl-NL011", name: "Колетт", gender: "f" },
  { code: "pl-PL012", name: "Марек", gender: "m" },
  { code: "pl-PL013", name: "Зофия", gender: "f" },
  { code: "ps-AF002", name: "Латифа", gender: "f" },
  { code: "ps-AF001", name: "ГулНаваз", gender: "m" },
  { code: "pt-BR007", name: "Франциска", gender: "f" },
  { code: "pt-BR008", name: "Антонио", gender: "m" },
  { code: "pt-PT011", name: "Ракель", gender: "f" },
  { code: "pt-PT009", name: "Дуарте", gender: "m" },
  { code: "pt-PT010", name: "Фернанда", gender: "f" },
  { code: "ro-RO003", name: "Алина", gender: "f" },
  { code: "ro-RO004", name: "Эмиль", gender: "m" },
  { code: "ru-RU068", name: "Светлана", gender: "f" },
  { code: "ru-RU070", name: "Дмитрий", gender: "m" },
  { code: "ru-RU069", name: "Дария", gender: "f" },
  { code: "ru-RU503", name: "Зина", gender: "f" },
  { code: "ru-RU504", name: "Федя", gender: "m" },
];

/**
 * Get all voices that match a language code (by ISO prefix).
 * E.g. for "ru" returns all "ru-RU0xx" voices.
 */
export function getFreeTtsVoicesByLang(langCode: string): FreeTtsVoice[] {
  return FREETTS_VOICES.filter((v) => v.code.startsWith(langCode));
}

/** Default voice — Борис (Russian, male) */
export const FREETTS_DEFAULT_VOICE: FreeTtsVoice = {
  code: "ru-RU066",
  name: "Борис",
  gender: "m",
};